### ISSUE TITLE
Feedback command

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/hazebot#93]
Would be cool to have a command to give feedback directly over the app.

Like typing: "Feedback: This app is garbage."

**Comment by ianhoffman** [comment]
This is currently blocked because we need to store more complete data about which messages a user has sent. Right now, the user would need to type `<CMD>: <Feedback>` for this to work, which is bad UI. In the future they'll be able to type `<CMD>`, we will respond with `Enter your feedback:`, and then they'll enter their feedback.

CC @wdanfort @emjgreen

**Comment by emjgreen** [comment]
One thing to think about for this though is, what happens if the user types the command for feedback and they receive "Enter your feedback:" but then they don't send anything. Or they forget to type their feedback and then they type "2" for Current AQI, but we get emailed "2" as their feedback! CC 

@ianhoffman  @wdanfort

**Comment by ianhoffman** [comment]
We should think about those cases!

For the case when a user types the command doesn't send anything, we should probably stop listening for their feedback after an hour or so. Or we could prompt them, but that's not MVP.

For the case where they type "2", yeah I was thinking about that also. I think that's OK. If the user inputs 1, 2, a zipcode, etc, as their feedback, then like... damn, that would just be weird.

WDYT @wdanfort ?
